# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Explore Web-Development
email: d.rudolf.von.rohr@gmail.com
description: Tutorials, Info and more all about Web-Development. Especially Pimcore, Typo3, Javascript & SVG Animations etc.
baseurl: "" # the subpath of your site, e.g. /blog
url: http://dvonrohr.ch # the base hostname & protocol for your site
twitter_username: dvonrohr
github_username:  dvonrohr
linkedin_username: dvonrohr
facebook_username: daniel.vonrohr

# used for opengraph
fb_admins: https://www.facebook.com/daniel.vonrohr
avatar: /img/profile.jpg

# Build settings
markdown: kramdown
