# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site title
title: "Full Stack Web Development"

# A description of your site for social meta tag, search engines, and feed.xml
description: "A Blog about Web Development and Design. All about Full Stack Web Development."

# Tagline near the site title
tagline: "All about Web Development."

# The subpath of your site, e.g. /blog, for generating urls
baseurl:

sass:
  sass_dir: _sass

# The base hostname & protocol of your site for where absolute urls are needed
url: "https://dvonrohr.com"

# Site navigation - each item must have a title and a url.
navigation:
- text: Home
  url: /
- text: About
  url: /about/
- text: Archives
  url: /tags/

# The shortname for your Disqus site to enable comments.
disqus:

# Author information - author info at the bottom of the post
author_name: "Daniel Von Rohr"
author_bio: "Daniel is a web developer located in Lucerne, Switzerland."
author_url:  "https://dvonrohr.com"
author_location: "Lucerne, Switzerland"
author_image: /images/authorimage.jpg

# Sidebar Add banner
# banner_url: "https://dvonrohr.com"
# banner_image: images/banner.jpg

# Sidebar newsletter widget - add your form action url for MailChimp signup form here
mailchimp_url: "//dvonrohr.us13.list-manage.com/subscribe/post?u=8dcb9fb919d2a709ba646a3ee&amp;id=1dbbc253e8"
# Social links in the site footer
twitter_username: "dvonrohr"
facebook_username: "daniel.vonrohr"
github_username: "dvonrohr"
codepen_username: "dvonrohr"
linkedin_username: "dvonrohr"

# http://jekyllrb.com/docs/pagination/
paginate: 5
paginate_path: '/blog/page:num/'
gems: [jekyll-paginate]

permalink: pretty
markdown: kramdown
kramdown:
    auto_ids: false
